name: Pull request
on: pull_request

jobs:
  commitsar:
    runs-on: ubuntu-latest
    name: Verify commit messages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run commitsar
        uses: docker://aevea/commitsar@sha256:a568c58c7d5c79eeb985dffbe8d0531ea4c26253509589c45c748244e4175030
